name = "combustible-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

[vars]
JANO_ALERT_URL = "https://cos-agent-worker.carlos-cb4.workers.dev/fuel/alert"

[[kv_namespaces]]
binding = "CAPACIDAD"
id = "67bd8d72166d4f46b046cf0fc3286b93"
